name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push backend image
      run: docker build -t benjames9/handemonium-backend:latest ./backend && docker push benjames9/handemonium-backend:latest

    - name: Build and push backend image
      run: docker build -t benjames9/handemonium-frontend:latest ./frontend/handemonium && docker push benjames9/handemonium-frontend:latest
